regenerate_html_job:
  cron: "50 23 * * Thu Europe/Berlin" # every thursday at 00:00
  class: "RegenerateHtmlWorker"
  queue: default

check_websites_job:
  cron: "0 20 * * Wed Europe/Berlin" # every wednesday at 20:00
  class: "CheckWebsitesWorker"
  queue: heavy_load

# should be closely after 'check_websites_job'
check_unreachable_offers_job:
  cron: "0 4 * * Thu Europe/Berlin" # every thursday at 04:00
  class: "CheckUnreachableOffersWorker"
  queue: default

seasonal_offers_job:
  cron: "0 5 * * * Europe/Berlin" # every day at 05:00
  class: "SeasonalOffersWorker"
  queue: default
