regenerate_html_job:
  cron: "50 23 * * Thu Europe/Berlin" # every thursday at 00:00
  class: "RegenerateHtmlWorker"
  queue: default

check_websites_job:
  cron: "0 20 * * Wed Europe/Berlin" # every wednesday at 20:00
  class: "CheckWebsitesWorker"
  queue: heavy_load

# should be closely after 'check_websites_job'
check_unreachable_offers_job:
  cron: "0 4 * * Thu Europe/Berlin" # every thursday at 04:00
  class: "CheckUnreachableOffersWorker"
  queue: default

seasonal_offers_job:
  cron: "0 5 * * * Europe/Berlin" # every day at 05:00
  class: "SeasonalOffersWorker"
  queue: default

process_tos_declined_emails_job:
  cron: "0 22 * * * Europe/Berlin" # every day at 22:00
  class: "ProcessTosDeclinedEmailsWorker"
  queue: heavy_load

process_tos_accepted_emails_job:
  cron: "0 21 * * * Europe/Berlin" # every day at 21:00
  class: "ProcessTosAcceptedEmailsWorker"
  queue: heavy_load
